sudo: false
language: node_js
node_js:
- '8'
- '9'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '9'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-publish.bash)"
notifications:
  slack:
    secure: zKZNi1pX/dRcrygUX35fLEr//7ObM4H1wWYmzJ80DGWi8OUnTjhwAwD5ukZZ4n2774Ve8LVHvic8jKcnM2yDSa7myxCsZTjTiiKcg6x5Si98fBN6shBL6MILPBh/aCl5h6SH9H6tRZkpq9TYBRZ5FSC2RgXb/tW4UgTJvDier2kzDuea7oCLZqjrEdB2Fwrb9SmkWHlwvgIn686xIKsMTJ2kg/fJbO2+Um1MSajK/sIN1cF/IwFiV4WGSSNBQ87yEBJWSHq24C5kK7QEiJw8A2S9xelR48hNsVT56W6l+PmQLW06yNoaNcZ+aK83pN9sQWKlyBQoh5ElGz0xRmlbpbUnFpR7F+tAJbbz6oDzwiHd2ydk0uv8/gkatr+TuKR2DnX7WbzsfCLM2tKESgPBSf/KI7dXUdhgyyzdHNwxUiOTMITv3VTY5xINhO9Vsz3azrOl0qnZNbcT9kBCYozMQMzFXsKFMwqxh42wQp2b1Vv1lBHj1IS/mSPZ8tXg/UZqzcaa8te7HUM8k7AlAZvIh41YgC4jsL8jUcmWi4VAyGKQYJvuWZn1puBMtrC98cmGjyGXknM0dGNRv58MRoH79fegsjfD+n2LVjhm9vsRs6/O9wxMd8lxqucxcUvg5WnRb3CxGbiU1XKfM2zYYzIXoYunOMOFLmMwfXGvTR0BloU=
  email:
    recipients:
      secure: fPP9Mrlbx4p+uFqaz0wZG32/SYqVzfpE7+Hxao7UuB2icZgdb25wz01AddolL61sveN0orEO1nqXKSTIXVGunMcH4B61C479GiAZ+RaKuIu3qkPNKZDH4/9CbErGXhbiM1tjpY4aul+RJ79KegUfDrOcuuf2YEyqYlrT7XbobTHSt7UqziGU8ANXHeHF+Kii5uFJAj7Rp8kvJTXlYSEtsw1jWeuX3mRdHoonz6wLasOEY2qfBzvK7+Rz0c2gSVEoOccrbAR0Lm2XLQKSYYAJXsS4sxWIf4mW9iRB8C+mMrK/lYduH3+QIUbRtollq4HA0JWm+0fBpy8/EVt001Po1KWwk+ZaSdy67NlEoabILCEgF2XZM6uKz/0zUWjDyP3Nr1mqe6iHgq+JAc3f7wBeAPi7b34lPhREx2Vky7SOatoeHguOWl5hPYfZA1R1VofNN53I1SmPNCd+pyE2DBvJpG6P/l5xYjSyolYpoS9bTS/m9BxEGNa/8qG++fQoQ1v/5JHDEpQ+gWYb6P/wUPqhmZTK49aBady6E6G9LtNIRSGrWpH2//RwQBRSxgUi8XkBKN12OydXac9MUZVP6AefDGdUcdNKLo4Vz0VxYkARx+azGk5+m43pQuw9FMtAr5rkQS83gS0TT1svsdKeaGciCNYhwsanln1/nsvmZKcvhSQ=
