sudo: false
language: node_js
node_js:
- '8'
- '10'
- '11'
matrix:
  fast_finish: true
  allow_failures: []
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/166faa4ea598a807629e87949e6085ef467e6560/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/166faa4ea598a807629e87949e6085ef467e6560/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/166faa4ea598a807629e87949e6085ef467e6560/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: UqQuazt4u6Ip6Ii/oO0ePnBZ1DG36iGymeG58DCP5metGiRcmXJC4pUSqXbajjWu2mR9Xi7Djk1lvfVEeJYX75GSY8ATV8nFoukFQK16VlRgOEYS+DOPRCkg0SwDsPwYFVQ2mPi0tiYwQdH6JwTv6nvIvnaYtgmTOnGkiMzDgY21Jp+jRfVXVzQJwsthzJVf3Arm/RoybU8xonEFb51IyCC5r83Y9mQuQa0V0BOF3+GUdT47/8p069mZiXp2l/uptY4hJBMCioye1UitF2IUPrLBYAwDJE2C9sICrOsDeQuG0eOmrq6Zu7elP2cINMVEcHJC0lg9uAk8/kKk8XOsz/1LZdP/lE4yX1Ga/Q7EhQg064soc3NUBP/aWFt/f6PvmxSfIrm45it7qBnP2gSWGPKYaj2n/eDNJGV0BGQn8V7FuaOLqVxzlOJn//lBFejcrnxScColRI1E+YuHq7zl3SQi57yJW7CHl/CxESzTQhX4U1k+35aO1RpKAQy1huYXEnOvf9b54YLtzTNJ4y6D6Li68jxRDmwrWfIPx50BV/ulenJoqutri0KqE2rLHThWDzoOydIuh+6c7xBP2cuTzKVA9+96iZWDnolWfdZDx3lk14cSnVNkQobUphV+D3B+suJHDZfHI/WTc2bqDBQkshDPebdUwFZP3wTxZJjEsFU=
