sudo: false
language: node_js
node_js:
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: oJX+GWlpswDQTb0aSuVLMcI1jOjljndHt/7dcM9PDvvfb1VQLsM8paJMS8iJr76PCLLq9+R00bIur3doCKAFiw4t51LkhGNJN5K9WdIlxP554C5Sg+MGTkflUHCZbP85fG9BG2cmCzj6ssAuAcVHC1a5XlC9PI8cYvPH31MLjNiIeKi7bgoa6N31sycEDHCz3upBYMghC1NQFJAz/3mr59fS9PtPwZVoKpauWDsZW+PTFK+JladuRKu8WBGTxBk2btW2aYhCQNxt6++5YjTqAc78FVNTmWaGaaeE4uqifOETpkCHD0tNPnRL038y4c6o+ulcIaorx1GX0GYLSpzamtwTGmt+KPesAnWLYAxfT8kj/p45c1FKviTf84dNqQrjOKC9v1DlMM0eZZAskMtVMnHHCzEaNe3YedsVs2EN4SZHAx7rgfTxXNN7ZVardp+bjOhTltk7opC4b69jzm9nYOs1f8UIKpv2Wb0ZAPl8A4sC9kFlpp32lA1LOfzAqxXSRtc7AUQveq616jCPpMRQOPa6x7k9xUmpXK55UlUN8HABS0fbaMUujDdvsHx+G8V1kAQrWB7jtW3JIt003eqqug/E20qzdWIjffTyNUDWcaklXc2HZQ8TWyfmzCHAUjIQmSxd/+l2ptt3L8cHIcrsizrkRVxzhEIhHUekHHE1tbM=
  email:
    recipients:
      secure: xR7dDVa4ZuSdizlF5pI4Fjtn+Op/QXWe3DdilqsjQV6UovEHTYpF0HJmkHuHnzmtZG+5uusYuJ/xU/Z5o1QWmpO/pz28ECepVg2305vLhF2olkuxlk6B/yBbQwIVHLbymc2lx6SeSvNnyTzbB97pg3J+v+wy/g15L/By+z9G4DXy80Y/Twk8fzxYmtvpch95qBH+IVbfVbwckvQYferK5TzuA7qrHcJtj2VO2Hr2pOTWlnZKwROllRTCPiS+5qMqULSWw0fW/OucdG6DAfHEin/5nqMJQ5EGt6NYf/KljQ4yO8ph8aPpI1CDQS/8or1Nzf/GTmjfOp/4Qjz51KIFLkgDqJkpzqsJ4BhlZGRV0CG4cRpNVQuu7bj7PE4LUF0YSRYqzmdSrLOhJ6tr67uO6dms8tISZmM/+Sfn8uRUNlKpGrNzs3ejiGqvBkRLb7ji7WnNv9sLsqtvdvDDgb3xg7edWwcjOK+pUouPj17Ig8+NnJMerrgohbcK4eKrWQhyWInN4q7SD54pd1QRfeLu2aUOtu0PM+08cY4Zbj+NSdugA0NYPuxtQTrgKnjNk/8Zw9VCKD/hk1oKVeJG/Km3txFzI935hTxYb+devXDGSwwyW1W6oZ8peRm1wcGHGNxKi2nUHmbLSmEU7W1tSi65c+zC9sykIMCmfGbNfXxdJNU=
