sudo: false
language: node_js
node_js:
- '8'
- '9'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '9'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/0f51e553b3cbf235cd15e2b80951212b5682036d/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/0f51e553b3cbf235cd15e2b80951212b5682036d/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/0f51e553b3cbf235cd15e2b80951212b5682036d/scripts/node-publish.bash)"
notifications:
  slack:
    secure: nxk20vZLdV7iHrqQH3AuTBjHgeOZXkcjXYUUrbXl2iNLQv9zItKufYCV6EbKhZAgZ3sbXsJd+IfI0JinW3wKb/XcW0c0hMzouQYtwrseCrYjQECiZoQGPwtQ3PN56BrGL5B5jGOa6SAkEf1HT5rZEW++pRRxCbXmjTdojhVIyKgEAxKT4Nq6ylJj1EuiKWeElH6LEWincuDWqG7JFup4FRrpeTYptFsznFGixUUgHLaNdhfcbskXfCDdTO7pFLpiCE3WMpxGIr7Jt/MMuB9wkZ9yJBnI6Soci7lmHYXtL2e/SL10Y5/zdhzv/UJNKU81J1tk8ZUiPbaM2CT8V6g1X2+cy5TsaRsy949w1aQM0kqBxbH5+oeW9ur8zcFP0eLVfCqxbBOMmyug8VEjAZudQ7veZO9zqB1iXBA2XPMAIdX3RI1VgDyLVzIU5qiFnp+0QHmIH46C3088zuGjj/GXoz5d6Kjht9t/4wUlLlVbXp5DfZkNOv/KMmlKDleYEQXVBP+FD2CPlTilaFiXJ3BiL+0OTqotAoBimxDPqoSMSwCeTkUgcGZFnI3LbgZz80XhqTFJELhPdLc/CYizzAG/FTWuUR1M8SdMH6OxOtHQYdI5fWhNYaQhri1Pxx3SqlF/pRKwOBa0JNnqNgKqe8c2K/eC2tHkdPWvjhdV6RvM+iU=
  email:
    recipients:
      secure: dz/0n4TvXWY/2Kh0CMyI6NCub6L5dIB6KZmyz0xrMLLHEGHma7rWcoUeoGF1q2XzSR4jQYrR57+CED7OX573GNDVXcf8PcplIk/bdxbzolL18knLan2LP4E4v3KzSdFfQ0ctSEdUWSpVOoDAPYvHWN1iiCAfW7VLyjiFVJ72ngfuJUN45K3cjKG7VwVnjjZO2h1fpPJBbb/XVJmkNfcBo61a6tZFW+CP2hU4IsWG8ulwJ9G0vrbYX6Oi64m7O1rk52BApcbcfqN+qsNUQcjj3Etk+Ww2nY+JEhEV2rmm75q0f6Y+5PH+JkGFlKhRNTfnKNKwMqCSgjj7BGVKs82KyJnf3kmrQNJeJ1dn+yzPDdDwq81zVNcz5A3LyCW657V0NkYH4e2QW065NHz4ezmHtyyfRpykp/CDUtBNpMkk+l01kvlYYbdZEdmhWP+DpAlZMn7p1lGmTu+6cGTTkpyobLeUlbUsDBCpaE5FHQ1ixJvV0pTFZGQiezguhOWjfGqPbHWuhJuJ4UFWKK60us0YRRlDuRjjvliI6+BOIaqzFhMPUjIxTnY+heDDYzODNpXpRtZ6TBjLuvM9DAJMuK4klGG/RjsGWZOUvzqxhumk1GI2tRFhOWDZbrikLJrW6cJXL0TbVLidlNIQzRF4QuYuCPh7/PQpml3UKzzn6BSIkKk=
