sudo: false
language: node_js
node_js:
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: jt1cnmQfdvhR2DYUE7bU65366P0YMFUtBSalcxWgkbqgP/x7n3terEALhMABEyDmICG1ZXsr4FGtrqsdb7DMHUXIXq+0Py7gNpkV47QLJMmHWdzaGQMM7vRC5pNFqQ/0cGmCzTblK0Uuox8OzRDU6646pka+7scd4d4yXmNXXzTCzaKa6/CPbnGZO0r2jgqfCwf45YROwxAdUP+QOVSy7SP72P2rMWhBdSyTp0QbuGG+0SXIVIb2b+hHIRpLAJCb0KoDt5huqmE/p0MAKmPmJHRTijC+90tkkZjNR6U28Nkzs8QmP+OGiWJWu7wqPUrX/Rz1kshxqiL8AZ+n6u79xpt54uy4b3sND2O/FdDdcL7TDtT506auMAKcyJ2LmThQ3YEHen8E1xM3j9GKMSjt3FAf/FzDr0qnEypeHkz9jBJrI0gCtd5baGvLwHUdDABo0YG1quug28+5ZR1xB39Ek0tVHbQ1gAvrHj649wyDoJrpz5XVE06qbFJ/dBqK1wYUO4/e8UgEK8SiX1PJ51r4Kq++/UVdgxYi3+dXvbrDGgfsMNqmjKs05tZmhUWpFritDPgZz1934AZB+95w1zrTGDm3zJnqnJPxKRQ/QLVOcSUh0xvv91NRBjJjbhQ0VxkPM/bAbpNmX/5YlOWvEPxfGH5SVrfix8Jrc5CDQ4OyY1Q=
  slack:
    secure: JFKdpn2Ntu7DNYEYoB1QpZNXXB5fWteKKMaKHaSwoFtOpS6jeP8dpq/3BNdNQm73XoGD2qM1TPHmD0UwFfqdN9SVdl+oCnRmdx2qg/AciQ60/nOU1LpgG5KkC5dSaVGcdjAi72cJioVMGoo9XD82SbEcD6ikKs2v81vPwDBdSnXep/QgOBQGAmqIjoa15Xw/bK2w0Z6YhopRuX9cJvty1n4kBT/+dUhkmmdI5JF70zL4dqeWstwtMZOBxRN+hdhF1DCSUs59emZ+8o8ANytFmsBToJKeORtX4pJ2NZexsDOeP9tI3QQgMXUDCLplMNDo5WZNjVSXkERfZn2RsWT3tVRMgvxCwUolfaoECJEFt+qi1kxT0o3vPF8cJPDTEZkjbsz0FiWyM+NDqCoQc3tPjpV7Fmvx8sX6+4dUca/sPtTAsmCbBQrjo7CcXdsAk1wwisrTS+If3mA+bk44icddfngyEk8zmRbr5IAeeOQ/haZVZF61NPQ5aup0UIJocEGcrbk0HtAjbUM0xCxGc3WTmeIlN7BeLELxRDBG8ZlSObmaCYf1pGtTIlaXPALrrHGTUud/KBewNrOzB3QmyRnUhKfZU0UGvizs7Qk0AiMGqNSlnfP2ixCqj10DKllUhCQcWKbBu3rx5lMgRrsbXn0U24JAe7cVXgovB8nsCoNGop0=
