sudo: false
language: node_js
node_js:
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- curl https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/npm-upgrade.bash
  | bash -l
- curl https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/npm-install.bash
  | bash -l
before_script:
- curl https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/npm-verify.bash
  | bash -l
after_success:
- curl https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/npm-publish.bash
  | bash -l
notifications:
  slack:
    secure: sSNheySHQpcV1bKWj1H4w7AXjSBHpBFOPGkH/e/5DgSwa2woObVEFGqGd8P+hW9rn/TpTv9nJlXsip5lTjCRjHIf5wFu96tGKKzVK1bhllZwenQg6/1kA3vrUY5BWB1ubrMGRBd83mmCOyMkVIJCedRtqjeQZA4/oHDVhpTVzfgLzlDI0cUp6QOmkq/g1JljNKqrVTVqL/GouKk4xbOISfK9PzMZWPhjYPOBDrCVcDyyiRJuzYBQ9fv3qHNmXO5IegZ2vuWKSCjOWZFhRG98yJjNr4QsRE/H7hvvx7Mk30RnbYcp07e6cvqOcdVmyMb5MenohuxsHbOOrHzB1Hr4crTt/El12eMNQNGAKlFzfDlFL1iypW19JGALdtPc1fCH8qH2GEGuYK8c5s6XQ6TziIewA2kUuvVgVMpzBxmlMqHtJ2JQDkk3J6MlIKCUkc4/zJibbSW9vRLUp6ybJhuAvkBEIK0+QowJX40d8BU3fGzOHHExK+UclPdotmEK9t+jpvzmIvqx/YLkSZ3mA2NANRaX+xpZ05C4F3O2dPlkuyamcsjThaizsF8BRmUud8XQPIKWJgXY3ousNeZDQ7Z9ol6KpQrEDKw15g+lCriNdW6246X+sDxCd+E/QKy1I3IsGaZq5hGRL1fMlqXA7g6DPzj8Tlm1EpsoHwEjRRd6UFM=
  email:
    recipients:
      secure: B4GTuEcXTzNDpLqyGHwEeSXzqVchTT1FKxHjYiy1GRkIeZmjiOtJunN4qDbAT6f5acEbaFOwRWTWoMP7qPWecWMsOWZTDdomCnUPR72d6S9WOB6w9VMjm4VBUYIahlvp6K8T0wX+XgXM/de3evRwrDaJgrJSSqBFNt3S+ihE6tcxfar4gxYt8oAICBrirlLaBFKgipO7cIzNnWZ82ecy0NkS57XE37ffp7h1rrAAeJQrGvICbjGdHiPD11bL8Yo8OlpAOZLfdYlon5jLNtr6AW+RHC50hXfvhf/N5h279jvun7bi4pysv5qHpa0m1149zSY1IOfkC2QMcmHW0h/SA39ZKhcDll031Brh+h6Oq4Kbt/jUiaKTbOzoUonUOXnmsxQit1Zd1d+NBl3UNMk6bs+7B/DRVlxwTTU4aNKJHPtc8ml4Pn1HIMZvsA1PJRT15L0NaTLsZf4Mdz6nzczSIAiaP6oR2j2EsiVP+kmLp0/XSKhLVFwX+CNKzHNWL0CZRQeht+Bfz2/VPdFRzElRxlyjef+zM/Hz8X4ByJAX7Aw9mq7fk5vhIbqxBx6k498Z+/c9oyhVDAPsNNor3nk8toHMqDQGTJwY6sRKB9TGQcKL0DmCP6/byWhZdFVG26SR7z8oitXXuTx/1vuZOPL1VF+WO9UTOfomaH5gUa1IFJo=
