sudo: false
language: node_js
node_js:
- '10'
matrix:
  fast_finish: true
  allow_failures: []
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-publish.bash)"
notifications:
  slack:
    secure: S1JJDQHjqZLS/+h9aTDz09jX7A9aOOoS8uEI1F1jev4mM8u16tMuo47pASqK2opVkR/s8pWuZwcORitijAD/rUQn5kP6MKX1ZIi6qcACltG5H5pEtZ0aw9s/Vd/BPKmiNT6tSfH3kzzTFUDiAqNYxDChkzotugtT4P5xHNF/j7X8KpM2DqqU1G0xRfdbnMmS0vLSwm0lfvH+dph9WLb89QsHNU+mzzsZBFp01aY2pNly2meMAsT1Jcn9PRc5AxsVbyLFOczMGX0oHaQGmUWfBYfNbl4J0uM2b6AvQZn1pSHg0uU/iY/t/eGoKuYl1V4yuwAaVCB6ldWryv5ysWyTlYofLpBcQtziF272r2pJhPS49M23TzPobYZoSf2zgoYUbBgKZe18YSdeJQejs3ueNOWPgDXTuB7LD+K1kDSN7cB8N74PpzJk2cT1FjGaSINAVo171DRk1ObaUuoMrIwPJdcQR5IW7mHHnCxTlpNU31Zir38MupwC87nWqLUi9fKexvJqrvpDU0L5oPafy7aR2G3yz7h/UWJyVY7EvKJ4pT1gG61jUh5k64FUqEwdxpKwTfUCPPe1EFRIIglmJY8zoBlV29lbCESig7XQrtCzF93RcRunAXA+mYcelG9S+Hd+QT1Gz7qluLHJhYE8ANG/yN96yhgR6/g0kWUqH26SdK8=
  email:
    recipients:
      secure: QWV2OGJju6solX+Op81uxuIYH7Gtj4ArsgtyTI8NlqmI1iTBLh/9th6Zw4iNe59aKdeWv4kBfufSu9wlDeh4R7u6GnBYVGbrzapvU7XEWOc0qn/9VA3aCLzKgp2p6QxvaHGviKN3CFMtkOmxsFCXffRuXXFb8RpwqsbOB52sXSSdfOwOIznOm7NobRaOFD+eJdkEnr4xpBpEYiuDUrG3qIE1cx4bwDlxru1nx23g4jV9Ns06rYELTpCKdEVsnlHLkNMC0Hf+5mC12wrC6L24JXA6HSgkyvdpxw0OAjYUZ73f7Sk0LCXDt0DTkzkoCnh0unr3IJWa8SyiXsUqdPbD91Vlmix9t14Siamn8LuaLMr9L5FwMGABb5S1Iz78WUoXJXDfMINJBGQWoIZJA4r1PVoiM6DCFu5L5RD6cCbldHlZf9qv69a2xyGB4m6LLn/5V66901AoY/UpqEkdbX3HZ28hev1szvvJbgg3HcvFHCbncLpwkW5CnqZNRboTfDjYhxjmVXg5+r4C6TFHE1TzV2twcX4glN0B/xvPlLT1Zh9RSg7/medW9UsiMhmSicEFzIxb7WVXfrPBUU1mawRMRA8RX+Mk/oWfXPZUbBBmkRIcyjrn6zKs0RMgGIUjoYLtx2jZ9qiGVonGSCcxZzDF9QppZ3eEt80T8h9QzXz8iik=
