sudo: false
language: node_js
node_js:
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- curl https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash
  | bash -l
- curl https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-upgrade-npm.bash
  | bash -l
before_script:
- curl https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash
  | bash -l
after_success:
- curl https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash
  | bash -l
notifications:
  email:
    recipients:
      secure: wf1Divhfsrb0vfLnfQn/SH8faaGOVd3MVHF8kzEcRyKSyJpSsonr84s9nKV4nIDyBlC1wuOwK3tHXl7g2B/lzdL5gHXl6+smOpAY6FdnmM1eBbUmFnhNjPjbIJ+jqJVMEy10RV1rNa5UPJWpljCWmk5QXFlv38ym5nmEqODwTT0H07+elgYnciXB/iL0CH62CclgN6X5++xRIr9NI0uaaRciJiMgXsyXrgRTTHL1pl5b1l/YEe8+FnF6azFaGlycdB7dH0TxXXYJ7S1a02mNaba9n6zADTz4jL4cb/Dc49wQ5mKaZjDNiemPQP51Hq8eIUhNZFe4V7m+nB70QxY/WFf/IgmAdykyiItV4jojjNNEcvwJ/GXo6v5fF3mNr0yB78jZA2FSk9PXbO6c+0WFh02uC3bRbYkCKaxBIcx26v8oa5hqMLWIF8hebKdoJnCFnbD2XPMd67WLGO/+IokIaPwiVz8Lf0Pz81JJtef1d/LJBgfPkCZgw2Oasx0KUy0zvBGJ/E76fSxQ/FqISAwgIyfgpq7rZ9RcyR+0br5Lb0N9nhY5jvLjTnSrn/+67vLifzbhAiF4krYqEQ0uRWbQjzjaXUiJRuKbaEQ4otRo/85gOtAQ5KHihO9ZBJ32Z/nuKwWHOcbyCH95psfwfBrpOhtd2FqAyMBWCZrY9sBEBL0=
