sudo: false
language: node_js
node_js:
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash
  | bash -l
- curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-upgrade-npm.bash
  | bash -l
before_script:
- curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash
  | bash -l
after_success:
- curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash
  | bash -l
notifications:
  email:
    recipients:
      secure: TR+lMFxVddPHSTUV7zTCxJHLfXQXxWktJa2kTey7b7erACMAhB75ZAfPDr0Xn39Zfvqz+mTbi9xLS4f8yBn/f8ySBX1EVdTK2/CIsbr8Z1xdC8vihxjlmNs6Xf4GPYkpG0T1p38VCRULGjfnXFAEzEzldsFRJqzw+3dPTPdFXhQRR5wtUmuwDjPUM4zohS9VJqykNZHGrgD3c5y+haCgz9Cr3QpE104Z2v/TJcGiciZw3o/KjmUOMllhAJzdEFsZhgg4zw7/97On9CrqS+2KR2nJuZND/KDy6sq6n/6Avs37tYT1Whfn3yzbcFV6GDvj+cgBzRvCJI8pWbkKhaBJXQFV5OjXIncRDg51LueNLpgPpx0dPmqLaCdkDJURR7XZputdocLly53NZyWGjI7oVQ4F6A4RqAKnQFVCJo68Xr4MnFw64Qqty3F/PyB8VA+SIZX1dgC3vmPRCXZQLMdkKNU+yF/n4dN20XnW4XJ1qBoYkCHDqgRzV2H7m6ruCJgPkphLDMsuIlfxGLLazUWULuWgy1OXIKAlQN3wibVz3g4KtVnjHICX6tQpS7ml/rpPV7vCOXG60g582xzm6e7e1VaOsKDzccHUigp1cBP8p/40rKiYPJfmUvzKK3QyXkD8FwpE1DRKS4OEQrj2PSrUQ6ogGcUjLWZ5nb1v5Ho6X2g=
