sudo: false
language: node_js
node_js:
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: gHfM9veQY9E8qdo4N1AFc6eq2ypJ6ulIBfh49enqP+fpdYQ2LwOZevwgOpgceqf0QSSAb3gcJ/1cpOoOo5LKZ7QKlxyJiBv1kJ3/91dmmWTmLRF/XW0BQ3T14EN5x7DX2KEGcCkb4DbnVmkPTEnFNF+fv04UvofHtT9omuwbb2MaXVKIbQtCKxuDf2mMZGykcMiyknSCfG5OR588AnQU76LWC8xzr/nMHtu3ss5+FNEwTyOBODD3DBSDsIPicC96Y1JlIlrxjJ2bSJapCrCXxWwAvchdO4yV6f/fIvxo2+FIWEy90LXiV/3YNph+TgLfZzt7Dye8UBLzXoRPBAxBUDIa/u7pAdE4dGXpSZfA07Xva3Wc+qFltNpFt0qvw+iNcrTMA8R0Ht/Cc14jJND6f0XgmEAZdofWagetn2MwzplfMg/smSVUl16uliZNqYeEYuU7OFQ1xSDu5MoqllPiU4tO+rbK86BKHig2RT4Nt8wTgNmnfX/7qiiqlzEvnqbprA1XZci9WCMXtP73z5veyNVK9/VtpKYezC/ClkLgnB/Xhdw9S/aWpIVxAL6ePZGGLpB2Ed10/fFCy10Nz02QMq9DSt+RstztNqTDB3sh4CtWx3s4D81qXk+gQtCnoP4AmlyXZ29oldzhoaYRn37Xih9s/9L6Ax73o7Vj/TAJfms=
  slack:
    secure: GCtR9Wo8m1iHvjos4ZM0ccYecc/MlvOkJi3+iyBAMzsMj0BuftCFXVHU8lYjcZ1QkF5q/XFa/y9y7Kga6jihFBuM3TwPrPTEpQTBQzfthUrngwOMzqQ6VSOW50f3j0NwUsexOcGHJWQtMmflfAkG2VLaahdwJ10yoG3eW9/CW5nxj6yB44ye5H0LYg/VT4vlsQJamSj9Mjrb1lNZZvldSbxKyUVX+aFOfYWwKYgs2Zp/Y5GbluyDZdO2NrO+2voIcHn8vOAUkl4yQ89s0NyZuOL9E9uM8PinocIcA+50tnDU2XruXaXZbT8QH30tXus/6z+JSRFfl4NZbG1MqvKGv50oEOpOOdzplUbt7s45sdZ/e4MLGzrmyEtdeVydrGuAdh1UVI6YjxqYks7MoRXbcgrAI/rhzWL0Z6xh7d3w0DO0M2oL3x9OGxMMV9i20osy6EIHiGPQxR6Bwiyz2pjCKk3CMa4bbiInwEdQickDo2bzK/s7HKbBwMXC7bIExKjB+NkLCvJlSXzEDLDF7I97dBUNmNGlcI1QIkANegBoLqTHZK8YegFwP16vL3HMhoog3Rhoc+Gs6EQWmZMTmUwGDQrNICJ/Jv42NW7NAIeSKPX4xHC8iWlbiVquAlUOGjfzYN3EIA2cEdOZFvjSEVotfHYTtvgdu8fI9O9fhFDej3o=
