sudo: false
language: node_js
node_js:
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: GG0C9sBhJ5n3SdK3UZu/ko2PZdrB1UmZGoOmGQlzRgHPxPynm6TMCeDNbeiL/py4XCXpiIm4itPf9OYCAoJ8OQe9E7X6NHh8PTWFGrwSvF/xt5ZNzcFsI1GnFshZVMSYOWeV9XDX9nE/PWyM2r2DePIy1a8vEUeSgKKjufIX5vLQdgzW2I48BTuH/SDsBJppaACKfKRIwnPYuoMmKTN1lj2ZzwI7+XioMH5Vq42TpdrXc3BV5JoU2Fp0rteJoq44ei0sSr9UAebLELNgKpDM5MaghIaRGjzVf6ceEH2i3HDJqElPxq+SLcTI6G8IvfiDp7evqV8gfY+J4pyljUuTJZPaErfV+pq5GjgH2J4gVs1/tRYmtR2WSvVn1rxyFQmNOaOjpvrnamPdXTsCRs+ovjvICkIsR/j7KRlf6gjECAtyDylMk82kSjPz1wcPcw0mrzT1tUn7bvk1iBulmY7DtjMRpXqX2Rz78DwLt27q04syfj3IUSFLC11AkDkR7GR2cDs25NDs+I/VxcM/p2Nje26tTDfqlWuV5eC8LH8yDr7E58zecfn90GuRhLxXZ6Eb9i5BWbpVG/85i+fwFPZRz/e/LPaXTMDQdfmd+juFfwAEowyDfU+NtPKAGwBs4Dy1pCoc/DpMmZNpDjAPkmKRo9lhOhkRQDag1p3cCQuiexc=
