sudo: false
language: node_js
node_js:
- '8'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: lg3fXMql4yUPxF+uTW8Uf5RwnbAnI0Lz/VkviLfAy9izmKnskG79aoW+Fu2ckj+ZDWRImAJtE4MScf4nCDs0r4vT4XfV6rTMSwreajU6Zl2UF+2QoIq2yud0zZ9tqY1nsXKGPXsWpLixasozA1fiAnXA0W71/VlCizTH97UpVpRB81EcwUQDcBBOYs5TOm6Rmt9HzGWHXVMJ58YDcsvodlXSEw2CUM9APmPXQz5xCrBKJrBEdFbFDN5R6qmjcFm9n73zpUIaXl84tX5/I480DsZknVx0zhkYiThjIVTEIgcJ9HwSAYVHvm/VVChLJmHedpK56IADDjfH5O4gqsBIxpckIWml181miXwttS/Ed6EgxNpaTUpoNE9YvASRtdacHkoOnWz+4XSQvWY3XkLkS8Y6sOdIMDf/S+7FGSd63Pxngh+5kknNJxtx0qWk+YR/xaP7TKMBwTyzKg0S1S0kpIMcsxCbbADzpGzlyb9thzrgCwzNVV2u/aWC/YAs2NayqIwn7CML/BgmlMQf7sq1piCwlRPpPYdDp6t+Gt1RhxMcn/pY7YXEbItg6YqIAdBjDY9W13mKx/iVuN91t9402+6c3Mbg5yMUm0RNrvsdNIg2jHQpe+Ha6Zj/Ha0oqFElnoAsa91L+cRWY4M7/ZkwLICZM0OltloNZ3ygGPMbI3k=
  email:
    recipients:
      secure: lh02wY+JpP3UbRll8+DMmv7+w0Fb9MsYI4X1R+Wcs7bCJl5v6gIihuu7SDsgaG5S6+oJCqCOBasmkZHTlfC8aXnANrEmpzFEympIKgLtW4/+EXzNX75YIRTLOvuKTlToP4YsuIMfm44a39t+3hpg/QtQEyBpQmbVAxXe9UTgVe4MrSmopTBbvC90SJpNoTF6piejQ+6QbB+1rJ5aX0yyWUYrO6skKkar/uweQEkYZ0kBA+wfLh2t4vawM092/5wx85wuusUGqDEXiZh8CGJgP9wcUejyXBVX44sG4LoQ3ZJ0u/jekZYXIm0BXNJfpP1jXx6xVERNNYxHj3Oq6a6dMkhEWSyt7Kug157LO7RF5i6oa3f+ANh47OdB14wEr8WgmPq34NGgXYNIg/y6QB1ByWEqx5UZebU+0njwjxYFo6Bz18n5cVowEkAzjGmv22Lm+uieCLo1Yqkdsu15+zmkadoK4dNJtyQneHBu2+manb8ZRP731stYStpF1DAfvjYnJt6mq8ycbw5S1Uv0yRomUSXNf+hea3vkJ8SnbobtvXJZavGA/gygOhQfwUchBY0kUWoN8eBYCzCzMrkRLmk8owMoLVlQUb+D9ltaUABIqCG5fjpOqzDFqlb9xc5ktSOVf90qdLchhpoBLypxU7/IjpD6XbTEA7M+T0vXWlKsgpc=
