sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '7'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.8'
  - node_js: '0.10'
  - node_js: '0.12'
  - node_js: '4'
  - node_js: '6'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- curl https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/npm-upgrade.bash
  | bash -l
- curl https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/npm-install.bash
  | bash -l
before_script:
- curl https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/npm-verify.bash
  | bash -l
after_success:
- curl https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/npm-publish.bash
  | bash -l
notifications:
  slack:
    secure: BHuxZnP28Px6/Rk0OvFU5nX0VN80X9N8bOllYcoOzwmobYHzXpuSZWO0Jpm5MCIIf567zMX/wnNeoy/wHUxwGN5XuLPkq0PXMgFO5vuJtmbMB1wQw3GRoh86oDsR7cgjL+11ggDOX1XB5JF+srSPDEkeniQk9fuioLhhHVYPiis4bPnAsdXpLkKU5+UhU4ksuYZGECvuVX41b/Lg+se+Mgeo82JW+x2Yw56l56edKOTMWaBbACLhlXJ/v3BbDBEBEIRLZ+RQhQisVNj+KVAK9ubZckjbRqMVf3n9vmXnVswWGvZncm2SL15PIE8qUjWHUMhzGTXyAvHm33Oj/IDbD4WnYt11g/vaQDRvBOS9q0MVRDuY6T1X2OQnFtYjTLOLZLzjTKxCg9xIKgnJb2h8uxEUjO7WsFwPZvgBs3hpx4bpfd+mYDC2Afs4svs4l+ODv1U1fKEZxLbggiRrbYSiff93eHODWnRxHIkE8PrGTkVNWaV3Z4J6tLHv/7tmAzLElLX1pHhfyiAjoTFGCuLeBTGJ6CbY2a/p8X52s1i7gtMCaNdXliGVGoBaBXFfOtIROyZh12Qd0DK9aQw33wT6RBxVIze4cKcnNywSn+FTf56pBVxpmRf86gaRw6VjI9Ps8knMgR5johfnSwKctQfQdeY4Qn+QNPxZ87vL7okm6dE=
  email:
    recipients:
      secure: KpFGl+PYVGDgAa3ig1abS7rSveKTlPrYcRHRwhLtWIqwv3FjYNNoUkm6BJ+eF8vs4nuE/QtcjGICqdJ25p+hVCvqanXBoiNK4DIYp6RbMeqRh8yOlITj3SylmEf/w5C0ZYsTtqo0FljN+PBxEsb8PCMktkuB/iTcPTkU6xIX4Ypc11F/nvWwLg06nbuOlZmL/kcp6wdF+hLbCh4q8jlwKPFD+OyQPjpNyVs5fVNEQFtG0IgQvEL12xgnTiFj7XSM8lZfgZGbu3cQMSgMDMO8LECk5DQQ4cvt6HsSpSGBPy9wHQLmakXpgadT6ALste9PhmNMG+Kp6JBYfy3Qr00DEzDmx6QaGuURzNr9L2VX2bvQ0lypKmKzBqi6OctQ09wSiSHGrsh2RcMOGNiLbOE+ALXi7ER18gNkRDtFgllknjQDv+AblPKrh2sGh3kGJ0myxEUVQwcohZPxOoNlH0WfsBQYEfGxs8E5+Ceq6Ty9Lq1U6ucWLC3v+Jkvl9G/2n43mP8o+MQKLflHJtXFJTUOrCp+lNq22mXAcsxXRXsaeiMqcvIEHELnpqojntCxSAk62jmD8l2YZJ842t0jrIanku41KaOGdMJPYEG5cJ6IFjfL7iivbqVtfxgz2veRrJk0NuG1luWb/M9ZdnaflYdSeGrLqktORZsKWgYQBNENepA=
