sudo: false
language: node_js
node_js:
- '8'
- '9'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '9'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/e6452af2b45ed487adbd002e9560acb759a1b5b9/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/e6452af2b45ed487adbd002e9560acb759a1b5b9/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/e6452af2b45ed487adbd002e9560acb759a1b5b9/scripts/node-publish.bash)"
notifications:
  slack:
    secure: sv7WcYPYoXrC7Tle2VE50HbfQJHUYnxk+fvBkuS3LrUwsJDip1/EEPcbVfgj5P64tjwpA/F8n2JYVQpGFchUrpkUtHwjZeEG1c5I9umZCFnBFkTwF7xjz1gzqEokVGA6/GvCUYD7rJgDMzdU1gfYsncIAIZW/FAO6fxM5i3smN8Z6mCF5JoIHV3tP42rmS151LFIThnPGaXxQ+FPheRItMfJO+Xga1sb8jJN+TxbD/meycFS54DpbCkjWcWeX/SCL2IVF+5tES62EUbk2mOubNYTzv/UMQJ2+KAPrzZDUUkzmmhPw8zr5/kbGzN8x21MyGAdpHNk0SusTRu1JM7nCRTaY+jZF0w67RUm/GZKt0lka29m7Wic9bFCIh9EfCmGDM0CeudyF8yVdDYv5yzryuXZ54Fx9GK4ZF13vf4yqEsBTsPg/KjOSs+d/fi7dtzuD3J77w9U34TFmDMGku3Hyp5k2lLkuV8x67szCqknhYbAuqKrgHSnVwqcBKIueog5XpbD3UwpHjFc8dapUMMcxTYCweAHtoigQt+0o7bfwha7IfDDMilREq5RQ7AW+692gmI6y/Bx/gc1pJfwfc9GGkD8FZhbnmj+/Jmc+Xiy850TplsgcIhnDPaJeo0RjyAgpbE9Vu8D7GCpaQ6mvbv3lwzaCLZmEJ3mWgQdoataOWs=
  email:
    recipients:
      secure: sCdZ4h60lZPBRDdcO6kRuWQtgqaniwOKvYSp1Ov/WAanj2PiwYtIoLysK7arWJhhnZ+UxKfMWaSuTCJ+DyNNQvLnZmfp4fZ94TmiEIFu8hWdZ81rCFqmf6t1cRMA/bPS92pqTMv92fikUAsZa5G7RQLczxrnNZAIOhTxD1nowoPQtnZNgHS1ec1gru8xcGCTqv46BoTOZqv3aZGsbYUs3yhWkAjvIMWe4eYg20RqPbjR6U93xPiCL3X8csgpSita25SkCaDDMA2pEan/HS02V6heHoa79uOvswdI3w3R1/UMr1jRuNY1y/Js98EuGb2ACjuFgSMIT6Ey5A3dyrmSN+b3zUsEurAg6ysuia+k+0ZoVUFAUxPN7FWXqbv9vBJVVtRbUT31bceCh8LAsW1hOHDl9ljweeG53v6Fubewig7q8IEfBdrkBptIXZC9+2db4PHDVUMeiWl5pd1upOqOEnteTxdS7qKDvMfLicibrHcP3jV3YiFHIrlhaxVRRFyS7xNekL2cIGZnKzJggce6kgTW3vhUlTtBtZfhys51DPG1l6vt8DzBRzcSwgq3vmVPUC+4zHX6/a7IBSElbjX+jyCu3EFU+npppS/DZivo/tuzvMhSDRCWnjwYjOUCLtu02gyBJbkR4nTcUSY77fN+6toQOvLvN1Qexi2ocGwYB+o=
