sudo: false
language: node_js
node_js:
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: h8HcLyV4m5JZ5qVlAyW4dKPZHt1nc/jAMbVjBr3iAeZ4ikcAPJDqABxl4+JvQ8o2ZOeJkJnMkBQDsKsZitEfC4tzdeO+wyrSQT06hjKEvjictPRnXzX4uaeCL1kcU/TMGUIheNfnNebUwvx6jOClcgFlCvFclgPT0sb6j4EeB4Ou2Yh3ojiUf2gGy6BGGIG5m8HWZ8VfFCTapiOf7mp+LuVGdULYkG5IuaPcZNyX74XYhqRDw2qavnhOXwB26133/ejrfyj0Xwrpp6e0xbPPm9t8vXcQIzoWaBwo/hZRpZhIwyvuuTlDIO5uHciiWZZjBfQVMUGcJ4dgP1r3cfJl0l3ptG7+uzOjjztYvsR5pq3e+iEoDiJ2vTDzbJM9X5FcE3b4fciYA0zTRiqNtrV+nvP/R0tHr1FplQqrZLGrBR9XO4vH2bn9ckdW7ofTymEQtjA1zjekdtEGG1r2Z96wLwwnDhhjhjwMXikHtBb4vYh+DXEMMTMpBsoWqDAyOtMrfJf5AK3eFVv9NdojPXs4aUKL2lOIGyTs34sgald2+a/esVvdEVfSk0s6X3fza9eSDDS/WfEp537TTnXZCYWelbYIPqzIiYYFTuOmNhQiUQEhW4dqinWoayUFIlr7+P3XhSIz1UHWrixOdRrQgXwMVZHaS77vXr3Wi8Nh6lmyLzQ=
  slack:
    secure: L7KanPO5okJjzhr43atfnM6c96fXJI1AS1Njnw+LYxv1YSKtj75xQyyYGadYuwRQRX1PkykISFSfmwBk+w7o+/h18h8m36gft7FRfJPynmlDRD8evRMAlB8E6imhRp/k1Ziad8MCZwadn96VI7d0t6kwiJyDaBDq7dA9Jeqz4VWZWNzfdsnunmfp529PYmWNLlxmD9zk13FtPYYZn7wAnxSFZOD7Ng9ZtAXRyulWEDvptqYZKJELIH4ZrUZHPkMOoLP/MIMgovT/At+5IpEPLrb78RuJFMJGP4mkTbRyTDDKMypvHFDfYtlcoxAeotaWRhPR8z93BknyulAQaJzQK2g2EeBGdDYWLLnHCTRS9NeVIegcNINIY3SeOF8W53NCHXOPXdDK7CzHjEJARP1DYUmCPhiOIlNLn3JLq9ABaokCZRs94c9MhZV8uwqJznh1H1hDsI1eJkqx8zpJDDZXaIxul8V1ANs/BIrakWz8ve8ONZQe4cRiXqmLOcSh/bkuNcmChxhLEomA9WOr0MS7/2xqVG/8+2/aCh7YtEqSs3ekCwMFNdFNz+OIQkoOA+dr/CE5m2bPsDjQBNRh490FXJ/LV3T6EjdTZfMXT64AL0HGBWSCK18u03awCVUc6+8dU9uLUXaX7/HKdHuTt6YungHjuMd5zPdlYlRDJzxIBM8=
