sudo: false
language: node_js
node_js:
- '8'
- '10'
matrix:
  fast_finish: true
  allow_failures: []
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-publish.bash)"
notifications:
  slack:
    secure: V2RBnMBsbs/vZHBuzJwYcef+d56Ewsl7sXHfONrHz8L3w7Lf0fLljlX53nEWhkOO3B6p103sbfD/ZLRBBpVlcK6EB7TWzrsE4Sknk+MdMiihMmTKjynPpSSqZcqgmQOmylKRMGT7HClDSSEOIo6oSJ+0clcYO21ebZl0CR+mWh8qx9cB2OeydpiukBPeZFf3GeoyjV0PIeoiZEiQnDAiOJXN0mPYOFj223/9zpkVTa9EEulD8ihuPdJaJKe7+gQLqC4GMsTIcPdPBIjmCkrDqSIcsfPmaspXCjckYSRbEzZZaQbS2rCkztETtNYzYBrTb9IG/DeN8QkeP7lLUK4FUciBVPFNCmg3o44ojCjrKXyfZsbhlOd2Kjv0a+oVS7nZy7RkangsDs9AsMm3Mjl+y2XQ/apXo4MW3Xs415mrWT/EspHIiQ1hBVb3VyIrfLtmOWFok8q2THsgQx4lWeZBngFWsODtKeCS/l9kEGGVhELbGuTTHuQ4FxIFIUWPYIo1Q8HImrOhQf/qhq0XsnT/NMiEQ8suRdZddOJVlv4X9FrX2FTZO91d6dxeXqNnDgFR98Uj3ePkwEf5L3vhITV5rpoDq7qupeXCUaNMQ0cCH/Cigi0aDn+TWIT2zXFphEFlZMoc7EfFzjVk/b8rjinEQkCj4tK5A2ES9jA81VWdY/Q=
  email:
    recipients:
      secure: AQaglRhOL7LmzAnMor0XgWU0KYoCdW9gUVPar8w+4HY+IEY3ps+ntONg7bKroTJnDM/gPVOYuK0Q5zx+z5B9E39MbrLKDo644c9TPJV9gS4Rl1/ZUlcWDhZeDh8AP9Sfonnzn/v23ekr7Mpbnz6AEwijeNsQyrIbn6j8ddQc/uQPT7wVbeyzsDHW5tdWXdM4j8pGCM9JX72IsfWmOlzVsbRlstlnipPi1H7uQxyOed4298NuRlqt8mmHyalwfIVp7fYtRfcUqECPsn4jRLGNt7lNME+ogXkqh+SXJHZIhPr8hBaSZxgVOpWsmUaBE/7XyOl5DWWDEABgsw6RqXqkAi4W7y1dAV9zYkk54EcThvAqPPC++kZle8gTvZUOqhSZRnSV13HigU9fblIZ0i9URqglzzVq4dn38yEt+otRYVKW3mA/cTZRLR3DLb81DvgWJM6ErtcYavOg9EdnjFAmgb5W6qRMqWnquU9F0TlSvCDdgdaFWyCnCEUGyubID0MEVDqwmGZmzzUDxI1UwEQZB/jBYtIaDusu4R6a4xkiPgiaAjyfQCSwUkBhY9/dfnxC3XNsVaogKPhxPCM/RCRAYXEpyn84Gcv2C7ITe/NmewmrLz8tbOIuCm7pjgTMNn6xcvrt1vG01DzR2/pko3bC4zHoCuQSqR9PtUnJTwsd9r4=
