version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '12'
  - '14'
  - '15'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      cNXqozEDuw8TP9IwoVKyfGEd33IQNwMi+RZdCsyeROv6Tvfxrqr/S97y81PTDmani9n9NGHG+KSJrEuet6T0rYbjyvsNsRk4ATzKIx9mbMEq4ei3I7gXkqopqQsZKbAt1c++LRBQJwQK9jfhR8DEs0kJRVe/Cr/S0ED6FO7H6IskpeFVMd9nAry238EYJVEJzrl+OKgfhU8ggQzhx5B+Mw4M+WfOjYQOQxxRSwfja8MqrhewodZuh7rE7vfda08uEheHAPn1DUsNSVjy78KsW7sIIJheyYG45aH2CcSw1msWCBeEaNbTQfMTklSwHRMiLKGzRKZYNI6HvSFOHH1cNqQSot5vZovsmXcqsyc9SIZzIoJ32S/xO9kO6uyhhho/KKDZSZcby1e2x4WSk69c8Hh2n/SlL86oSzo9fh94T+84FCJj9mHJqg9KrSIF/M5fzL7ULbZeSk0Oaje3GlV2jWUmj9WfzA2Z5nffVD9ennrXfdJowadhIKdevhtT8CLw8rSCWrLPE/smG/eZZ38lSuaTs2kClxtwzsMj3/qKJ02JZagRhpwnYbl51d+Ifyj+aJUqY3m9dVUavGT2owxt4stjSBkHbHvGBd9oqYu88NyFnNLNQ2Qu6sg1jZBuKvB0GYEClm7DzZKOmM0EgQ2hRd1Tp02ej5ojqIhormDIOGw=
